### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by mattlanham** [chartmogul/chartmogul-php#15]
Was just trying this out within the Laravel framework and I can't seem to get it to work as expected, it seems to find the Configuration class fine, but it's failing on almost any other, and I am getting:

Fatal error: Class 'ChartMogul\DataSource' not found

or if I try Ping:

Fatal error: Class 'ChartMogul\Ping' not found

**Comment by mattlanham** [comment]
I have resolved it by changing the required version to "dev-master"

**Comment by pkopac** [comment]
Hi @mattlanham,
thank you for reporting. I have just released version [1.1.0](https://github.com/chartmogul/chartmogul-php/releases/tag/1.1.0), please use that in your project.
As you say, in 1.0.x the classes are not there, because they have a different namespace. I just needed to fix one more thing for this release, but now it's ready.
